[features/AEKR-2093] updating scripts for add indexes-constraints, update vocab, update custom concepts
solventrix/Honeur-Setup pull request #38
Opened 2024-09-13 09:45 UTC by silviajimeneznavarro-edence

2024-09-13 12:55 UTC, petermoorthamer requested changes

2024-09-13 12:55 UTC, petermoorthamer commented on local-installation/separate-scripts/start-add-indexes-and-constraints.cmd
Let's rename this script to 'add-omop-indexes-and-constraints.cmd'
The existing script 'start-omop-indexes-and-constraints.cmd' can be removed

2024-09-13 12:55 UTC, petermoorthamer commented on local-installation/separate-scripts/start-add-indexes-and-constraints.sh
Let's rename this script to 'add-omop-indexes-and-constraints.sh'
The existing script 'start-omop-indexes-and-constraints.sh' can be removed

2024-09-16 14:43 UTC, silviajimeneznavarro-edence commented on local-installation/separate-scripts/start-add-indexes-and-constraints.cmd
done!

2024-09-16 14:43 UTC, silviajimeneznavarro-edence commented on local-installation/separate-scripts/start-add-indexes-and-constraints.sh
done!

2024-09-16 16:01 UTC, petermoorthamer approved these changes

2024-09-20 13:40 UTC, merged